name: easy_notepad
description: Simple drawing + notes app
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_painter: ^1.0.0

flutter:
  uses-material-design: true